embedding_model:
  google:
    provider: "google"
    model_name: "models/text-embedding-004"
  openai:
    provider: "openai"
    model_name: "text-embedding-3-small"

retriever:
  top_k: 10

llm:
  groq:
    provider: "groq"
    model_name: "openai/gpt-oss-20b"
    temperature: 0.0
    max_output_tokens: 2048

  google:
    provider: "google"
    model_name: "gemini-2.0-flash"
    temperature: 0.0
    max_output_tokens: 2048

  openai:
    provider: "openai"
    model_name: "gpt-5-mini"
    max_output_tokens: 2048
